// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ShellType 定义 shell 类型
 * @readonly
 * @enum {string}
 */
export const ShellType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ShellTypeCmd: "cmd",
    ShellTypePowershell: "powershell",
    ShellTypePwsh: "pwsh",
    ShellTypeBash: "bash",
    ShellTypeZsh: "zsh",
    ShellTypeSh: "sh",
    ShellTypeAuto: "auto",
};

/**
 * TerminalConfig 终端配置
 */
export class TerminalConfig {
    /**
     * Creates a new TerminalConfig instance.
     * @param {Partial<TerminalConfig>} [$$source = {}] - The source object to create the TerminalConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 会话 ID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("shell" in $$source)) {
            /**
             * shell 路径，"auto" 表示自动检测
             * @member
             * @type {ShellType}
             */
            this["shell"] = ShellType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * 终端行数
             * @member
             * @type {number | undefined}
             */
            this["rows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 终端列数
             * @member
             * @type {number | undefined}
             */
            this["cols"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 工作路径
             * @member
             * @type {string | undefined}
             */
            this["workPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 初始命令
             * @member
             * @type {string | undefined}
             */
            this["initialCommand"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalConfig(/** @type {Partial<TerminalConfig>} */($$parsedSource));
    }
}
