// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * ChatEvent 描述发往前端的聊天事件载荷。
 */
export class ChatEvent {
    /**
     * Creates a new ChatEvent instance.
     * @param {Partial<ChatEvent>} [$$source = {}] - The source object to create the ChatEvent.
     */
    constructor($$source = {}) {
        if (!("conversationId" in $$source)) {
            /**
             * Boxify 会话 ID。
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * OpenClaw 会话 ID。
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("runId" in $$source)) {
            /**
             * OpenClaw 执行 ID。
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("eventType" in $$source)) {
            /**
             * 事件类型。
             * @member
             * @type {ChatEventType}
             */
            this["eventType"] = ChatEventType.$zero;
        }
        if (!("payload" in $$source)) {
            /**
             * 事件负载。
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["payload"] = {};
        }
        if (!("timestamp" in $$source)) {
            /**
             * 事件时间（Unix 毫秒）。
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChatEvent}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField4_0($$parsedSource["payload"]);
        }
        return new ChatEvent(/** @type {Partial<ChatEvent>} */($$parsedSource));
    }
}

/**
 * ChatEventType 描述聊天链路的事件类型。
 * @readonly
 * @enum {string}
 */
export const ChatEventType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ChatEventTypeAssistantDelta 表示 Boxify 前端应将该文本片段追加到助手草稿中。
     */
    ChatEventTypeAssistantDelta: "assistant_delta",

    /**
     * ChatEventTypeAssistantDone 表示本次助手回复已完成，前端可结束流式态并刷新正式消息。
     */
    ChatEventTypeAssistantDone: "assistant_done",

    /**
     * ChatEventTypeAssistantError 表示本次助手回复失败，前端应展示错误状态。
     */
    ChatEventTypeAssistantError: "assistant_error",

    /**
     * ChatEventTypeStreamStart 表示插件 SSE 流已建立，OpenClaw 开始生成回复。
     */
    ChatEventTypeStreamStart: "start",

    /**
     * ChatEventTypeStreamDelta 表示插件 SSE 返回了一段新的文本增量。
     */
    ChatEventTypeStreamDelta: "delta",

    /**
     * ChatEventTypeStreamDone 表示插件 SSE 已完成本次回复输出。
     */
    ChatEventTypeStreamDone: "done",

    /**
     * ChatEventTypeStreamError 表示插件 SSE 在回复过程中发生错误。
     */
    ChatEventTypeStreamError: "error",
};

/**
 * Conversation 描述 Boxify 侧维护的聊天会话。
 */
export class Conversation {
    /**
     * Creates a new Conversation instance.
     * @param {Partial<Conversation>} [$$source = {}] - The source object to create the Conversation.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * Boxify 会话 ID。
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * 会话标题。
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("agentId" in $$source)) {
            /**
             * 绑定的 Agent ID。
             * @member
             * @type {string}
             */
            this["agentId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 映射到 OpenClaw 的会话 ID。
             * @member
             * @type {string | undefined}
             */
            this["openClawSessionId"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * 创建时间。
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * 最近更新时间。
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conversation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Conversation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conversation(/** @type {Partial<Conversation>} */($$parsedSource));
    }
}

/**
 * Message 描述会话中的单条消息。
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * Boxify 消息 ID。
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("conversationId" in $$source)) {
            /**
             * 所属会话 ID。
             * @member
             * @type {string}
             */
            this["conversationId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 所属执行 ID。
             * @member
             * @type {string | undefined}
             */
            this["runId"] = undefined;
        }
        if (!("role" in $$source)) {
            /**
             * user/assistant/system。
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * 消息文本。
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * streaming/done/error。
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * 创建时间。
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
