// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as service$0 from "../../../../chenyang-zz/boxify/internal/service/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "data-sync:broadcast": service$0.DataSyncEvent;
            "data-sync:targeted": service$0.DataSyncEvent;
            "initial-data:received": service$0.InitialDataEntry;
            "window:closed": { [_ in string]?: any };
            "window:opened": { [_ in string]?: any };
        }
    }
}
