// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClawService 提供 OpenClaw 相关能力（进程、配置、插件、任务、更新、NapCat 监控）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "../window/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

/**
 * App 获取应用实例
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function App() {
    return $Call.ByID(3304917659).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AppManager 获取窗口管理器
 * @returns {$CancellablePromise<window$0.AppManager | null>}
 */
export function AppManager() {
    return $Call.ByID(4152816186).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckOpenClaw 检查 OpenClaw 是否已安装并完成基础配置。
 * @returns {$CancellablePromise<types$0.ClawOpenClawCheckResult | null>}
 */
export function CheckOpenClaw() {
    return $Call.ByID(2841486999).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CheckPanelUpdate 检查面板更新。
 * @returns {$CancellablePromise<types$0.ClawCheckUpdateResult | null>}
 */
export function CheckPanelUpdate() {
    return $Call.ByID(2937758095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Configure 更新 Claw 管理配置并重建依赖管理器。
 * @param {types$0.ClawManagerConfig} cfg
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function Configure(cfg) {
    return $Call.ByID(4118344372, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * Context 获取上下文
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Context() {
    return $Call.ByID(4226482147);
}

/**
 * CreateChatConversation 创建聊天会话。
 * @param {string} agentID
 * @returns {$CancellablePromise<types$0.ClawChatConversationResult | null>}
 */
export function CreateChatConversation(agentID) {
    return $Call.ByID(544313377, agentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * DefaultServiceShutdown 默认关闭实现
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceShutdown() {
    return $Call.ByID(1437461094);
}

/**
 * DefaultServiceStartup 默认启动实现
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceStartup(options) {
    return $Call.ByID(8447853, options);
}

/**
 * DoPanelUpdate 执行面板更新。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function DoPanelUpdate() {
    return $Call.ByID(2860250088).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ExportTypes() {
    return $Call.ByID(1623521551);
}

/**
 * GetChannels 获取通道与插件配置。
 * @returns {$CancellablePromise<types$0.ClawChannelsResult | null>}
 */
export function GetChannels() {
    return $Call.ByID(2718586132).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetChatChannelInfo 返回 Boxify 与原生 channel inbox 通信所需的连接信息。
 * @returns {$CancellablePromise<types$0.ClawChatChannelInfoResult | null>}
 */
export function GetChatChannelInfo() {
    return $Call.ByID(2988689245).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetChatMessages 返回指定会话消息列表。
 * @param {string} conversationID
 * @returns {$CancellablePromise<types$0.ClawChatMessagesResult | null>}
 */
export function GetChatMessages(conversationID) {
    return $Call.ByID(362277814, conversationID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetInstalledPlugins 获取已安装插件。
 * @returns {$CancellablePromise<types$0.ClawInstalledPluginsResult | null>}
 */
export function GetInstalledPlugins() {
    return $Call.ByID(2961876742).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetLogs 获取最近日志。
 * @param {number} n
 * @returns {$CancellablePromise<types$0.ClawLogsResult | null>}
 */
export function GetLogs(n) {
    return $Call.ByID(1734461191, n).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * GetModels 获取模型配置。
 * @returns {$CancellablePromise<types$0.ClawModelsResult | null>}
 */
export function GetModels() {
    return $Call.ByID(600279102).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetNapCatReconnectLogs 获取 NapCat 重连日志。
 * @returns {$CancellablePromise<types$0.ClawNapCatReconnectLogsResult | null>}
 */
export function GetNapCatReconnectLogs() {
    return $Call.ByID(2013442153).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * GetNapCatStatus 获取 NapCat 状态。
 * @returns {$CancellablePromise<types$0.ClawNapCatStatusResult | null>}
 */
export function GetNapCatStatus() {
    return $Call.ByID(1484756979).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetOpenClawConfig 获取 OpenClaw 配置。
 * @returns {$CancellablePromise<types$0.ClawOpenConfigResult | null>}
 */
export function GetOpenClawConfig() {
    return $Call.ByID(3520174945).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * GetOverview 获取 OpenClaw 概览信息。
 * @returns {$CancellablePromise<types$0.ClawOverviewResult | null>}
 */
export function GetOverview() {
    return $Call.ByID(1684181423).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * GetPluginConfig 获取插件配置与 schema。
 * @param {string} id
 * @returns {$CancellablePromise<types$0.ClawPluginConfigResult | null>}
 */
export function GetPluginConfig(id) {
    return $Call.ByID(1776026285, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * GetPluginDetail 获取插件详情。
 * @param {string} id
 * @returns {$CancellablePromise<types$0.ClawPluginDetailResult | null>}
 */
export function GetPluginDetail(id) {
    return $Call.ByID(564040670, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * GetPluginList 获取已安装插件与仓库插件。
 * @returns {$CancellablePromise<types$0.ClawPluginListResult | null>}
 */
export function GetPluginList() {
    return $Call.ByID(1929709191).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * GetPluginLogs 获取插件日志。
 * @param {string} id
 * @returns {$CancellablePromise<types$0.ClawPluginLogsResult | null>}
 */
export function GetPluginLogs(id) {
    return $Call.ByID(98837236, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * GetSkillPlugins 获取技能中心中的已安装插件列表。
 * @returns {$CancellablePromise<types$0.ClawSkillPluginsResult | null>}
 */
export function GetSkillPlugins() {
    return $Call.ByID(218481615).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * GetSkills 获取技能中心所需的技能列表。
 * @returns {$CancellablePromise<types$0.ClawSkillsResult | null>}
 */
export function GetSkills() {
    return $Call.ByID(940035350).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * GetStatus 获取 OpenClaw 状态。
 * @returns {$CancellablePromise<types$0.ClawStatusResult | null>}
 */
export function GetStatus() {
    return $Call.ByID(3242596438).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * GetTaskDetail 获取任务详情。
 * @param {string} id
 * @returns {$CancellablePromise<types$0.ClawTaskDetailResult | null>}
 */
export function GetTaskDetail(id) {
    return $Call.ByID(3377374600, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType47($result);
    }));
}

/**
 * GetTasks 获取最近任务列表。
 * @returns {$CancellablePromise<types$0.ClawTasksResult | null>}
 */
export function GetTasks() {
    return $Call.ByID(1865642142).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * GetUpdatePopup 获取更新完成弹窗信息。
 * @returns {$CancellablePromise<types$0.ClawUpdatePopupResult | null>}
 */
export function GetUpdatePopup() {
    return $Call.ByID(699133221).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType51($result);
    }));
}

/**
 * InstallPlugin 安装插件。
 * @param {string} pluginID
 * @param {string} source
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function InstallPlugin(pluginID, source) {
    return $Call.ByID(4164125592, pluginID, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListChatConversations 返回聊天会话列表。
 * @returns {$CancellablePromise<types$0.ClawChatConversationsResult | null>}
 */
export function ListChatConversations() {
    return $Call.ByID(2692001938).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType53($result);
    }));
}

/**
 * Logger 获取日志记录器
 * @returns {$CancellablePromise<slog$0.Logger | null>}
 */
export function Logger() {
    return $Call.ByID(983389924).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType55($result);
    }));
}

/**
 * MarkUpdatePopupShown 标记更新弹窗已展示。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function MarkUpdatePopupShown() {
    return $Call.ByID(824730491).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * NapCatMonitorConfig 更新 NapCat 监控配置。
 * @param {{ [_ in string]?: any }} payload
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function NapCatMonitorConfig(payload) {
    return $Call.ByID(1566608267, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * NapCatReconnect 手动触发 NapCat 重连。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function NapCatReconnect() {
    return $Call.ByID(95604678).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * PanelUpdateProgress 获取面板更新进度。
 * @returns {$CancellablePromise<types$0.ClawPanelUpdateProgressResult | null>}
 */
export function PanelUpdateProgress() {
    return $Call.ByID(123677464).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType57($result);
    }));
}

/**
 * ProcessStatus 获取进程状态（兼容 ClawPanel 接口名）。
 * @returns {$CancellablePromise<types$0.ClawProcessStatusResult | null>}
 */
export function ProcessStatus() {
    return $Call.ByID(3350117591).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType59($result);
    }));
}

/**
 * RefreshPluginRegistry 刷新插件仓库。
 * @returns {$CancellablePromise<types$0.ClawRegistryResult | null>}
 */
export function RefreshPluginRegistry() {
    return $Call.ByID(2501054711).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType61($result);
    }));
}

/**
 * Registry 获取窗口注册表
 * @returns {$CancellablePromise<window$0.WindowRegistry | null>}
 */
export function Registry() {
    return $Call.ByID(1073634743).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType63($result);
    }));
}

/**
 * Restart 重启 OpenClaw。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function Restart() {
    return $Call.ByID(3066425723).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * RestartProcess 重启 OpenClaw 进程（兼容 ClawPanel 接口名）。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function RestartProcess() {
    return $Call.ByID(1319926960).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SaveChannel 保存指定通道配置。
 * @param {string} id
 * @param {{ [_ in string]?: any }} payload
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function SaveChannel(id, payload) {
    return $Call.ByID(3511102620, id, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SaveModels 保存模型配置。
 * @param {{ [_ in string]?: any }} providers
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function SaveModels(providers) {
    return $Call.ByID(616286499, providers).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SaveOpenClawConfig 保存 OpenClaw 配置。
 * @param {{ [_ in string]?: any }} cfg
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function SaveOpenClawConfig(cfg) {
    return $Call.ByID(1816196008, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SavePlugin 保存指定插件配置。
 * @param {string} id
 * @param {{ [_ in string]?: any }} payload
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function SavePlugin(id, payload) {
    return $Call.ByID(1344614258, id, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SendChatMessage 向指定会话发送消息。
 * @param {string} conversationID
 * @param {string} text
 * @returns {$CancellablePromise<types$0.ClawChatSendResult | null>}
 */
export function SendChatMessage(conversationID, text) {
    return $Call.ByID(2501988311, conversationID, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType65($result);
    }));
}

/**
 * SetAppManager 设置窗口管理器
 * @param {window$0.AppManager | null} am
 * @returns {$CancellablePromise<void>}
 */
export function SetAppManager(am) {
    return $Call.ByID(278808874, am);
}

/**
 * SetContext 设置上下文
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(2743912499);
}

/**
 * SetRegistry 设置窗口注册表
 * @param {window$0.WindowRegistry | null} registry
 * @returns {$CancellablePromise<void>}
 */
export function SetRegistry(registry) {
    return $Call.ByID(476817255, registry);
}

/**
 * Start 启动 OpenClaw。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function Start() {
    return $Call.ByID(391052524).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * StartProcess 启动 OpenClaw 进程（兼容 ClawPanel 接口名）。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function StartProcess() {
    return $Call.ByID(3302587713).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * Stop 停止 OpenClaw。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function Stop() {
    return $Call.ByID(567698888).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * StopProcess 停止 OpenClaw 进程（兼容 ClawPanel 接口名）。
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function StopProcess() {
    return $Call.ByID(1948308485).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ToggleChannel 切换通道启用状态。
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function ToggleChannel(id, enabled) {
    return $Call.ByID(1200616767, id, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * TogglePlugin 切换插件启用状态。
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function TogglePlugin(id, enabled) {
    return $Call.ByID(1637441743, id, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ToggleSkill 切换技能启用状态。
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function ToggleSkill(id, enabled) {
    return $Call.ByID(3040047825, id, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * UninstallPlugin 卸载插件。
 * @param {string} id
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function UninstallPlugin(id) {
    return $Call.ByID(2680098029, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * UpdatePluginConfig 更新插件配置。
 * @param {string} id
 * @param {{ [_ in string]?: any }} cfg
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function UpdatePluginConfig(id, cfg) {
    return $Call.ByID(2511145424, id, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * UpdatePluginVersion 更新插件版本。
 * @param {string} id
 * @returns {$CancellablePromise<types$0.BaseResult | null>}
 */
export function UpdatePluginVersion(id) {
    return $Call.ByID(1221368698, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = window$0.AppManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = types$0.ClawOpenClawCheckResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = types$0.ClawCheckUpdateResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = types$0.BaseResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = types$0.ClawChatConversationResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = types$0.ClawChannelsResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = types$0.ClawChatChannelInfoResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = types$0.ClawChatMessagesResult.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = types$0.ClawInstalledPluginsResult.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = types$0.ClawLogsResult.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = types$0.ClawModelsResult.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = types$0.ClawNapCatReconnectLogsResult.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = types$0.ClawNapCatStatusResult.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = types$0.ClawOpenConfigResult.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = types$0.ClawOverviewResult.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = types$0.ClawPluginConfigResult.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = types$0.ClawPluginDetailResult.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = types$0.ClawPluginListResult.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = types$0.ClawPluginLogsResult.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = types$0.ClawSkillPluginsResult.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = types$0.ClawSkillsResult.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
const $$createType44 = types$0.ClawStatusResult.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = types$0.ClawTaskDetailResult.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = types$0.ClawTasksResult.createFrom;
const $$createType49 = $Create.Nullable($$createType48);
const $$createType50 = types$0.ClawUpdatePopupResult.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = types$0.ClawChatConversationsResult.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
const $$createType54 = slog$0.Logger.createFrom;
const $$createType55 = $Create.Nullable($$createType54);
const $$createType56 = types$0.ClawPanelUpdateProgressResult.createFrom;
const $$createType57 = $Create.Nullable($$createType56);
const $$createType58 = types$0.ClawProcessStatusResult.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
const $$createType60 = types$0.ClawRegistryResult.createFrom;
const $$createType61 = $Create.Nullable($$createType60);
const $$createType62 = window$0.WindowRegistry.createFrom;
const $$createType63 = $Create.Nullable($$createType62);
const $$createType64 = types$0.ClawChatSendResult.createFrom;
const $$createType65 = $Create.Nullable($$createType64);
