// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataSyncService 数据同步服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "../connection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "../window/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * App 获取应用实例
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function App() {
    return $Call.ByID(128460695).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AppManager 获取窗口管理器
 * @returns {$CancellablePromise<window$0.AppManager | null>}
 */
export function AppManager() {
    return $Call.ByID(1123141438).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Broadcast 广播消息到所有窗口
 * @param {string} channel
 * @param {string} dataType
 * @param {{ [_ in string]?: any }} data
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function Broadcast(channel, dataType, data, source) {
    return $Call.ByID(59802399, channel, dataType, data, source);
}

/**
 * Context 获取上下文
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Context() {
    return $Call.ByID(963778567);
}

/**
 * DefaultServiceShutdown 默认关闭实现
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceShutdown() {
    return $Call.ByID(2944207938);
}

/**
 * DefaultServiceStartup 默认启动实现
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceStartup(options) {
    return $Call.ByID(2274848121, options);
}

/**
 * Emit 发送事件（内部方法）
 * @param {$models.DataSyncEvent} event
 * @returns {$CancellablePromise<void>}
 */
export function Emit(event) {
    return $Call.ByID(32369703, event);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ExportTypes() {
    return $Call.ByID(868942851);
}

/**
 * GetWindowsList 获取所有窗口列表
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function GetWindowsList() {
    return $Call.ByID(1569542745).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Logger 获取日志记录器
 * @returns {$CancellablePromise<slog$0.Logger | null>}
 */
export function Logger() {
    return $Call.ByID(2082339776).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Registry 获取窗口注册表
 * @returns {$CancellablePromise<window$0.WindowRegistry | null>}
 */
export function Registry() {
    return $Call.ByID(2190795123).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SendTo 发送消息到指定窗口
 * @param {string} targetWindow
 * @param {string} channel
 * @param {string} dataType
 * @param {{ [_ in string]?: any }} data
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function SendTo(targetWindow, channel, dataType, data, source) {
    return $Call.ByID(2115899071, targetWindow, channel, dataType, data, source);
}

/**
 * SetAppManager 设置窗口管理器
 * @param {window$0.AppManager | null} am
 * @returns {$CancellablePromise<void>}
 */
export function SetAppManager(am) {
    return $Call.ByID(621444070, am);
}

/**
 * SetContext 设置上下文
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(3971631343);
}

/**
 * SetRegistry 设置窗口注册表
 * @param {window$0.WindowRegistry | null} registry
 * @returns {$CancellablePromise<void>}
 */
export function SetRegistry(registry) {
    return $Call.ByID(1519839995, registry);
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = window$0.AppManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = connection$0.QueryResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = slog$0.Logger.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = window$0.WindowRegistry.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
