// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService 负责前端服务编排，连接管理由 db.ConnectionManager 承担。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "../connection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "../window/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

/**
 * App 获取应用实例
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function App() {
    return $Call.ByID(283310305).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AppManager 获取窗口管理器
 * @returns {$CancellablePromise<window$0.AppManager | null>}
 */
export function AppManager() {
    return $Call.ByID(311096048).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ApplyChanges 将更改集应用到数据库表中。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @param {connection$0.ChangeSet | null} changes
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function ApplyChanges(config, dbName, tableName, changes) {
    return $Call.ByID(1252209655, config, dbName, tableName, changes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Context 获取上下文
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Context() {
    return $Call.ByID(215077133);
}

/**
 * CreateDatabase 创建一个新的数据库
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function CreateDatabase(config, dbName) {
    return $Call.ByID(1430813979, config, dbName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBConnect 连接数据库，成功则返回成功消息，失败则返回错误信息
 * @param {connection$0.ConnectionConfig | null} config
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBConnect(config) {
    return $Call.ByID(2310763686, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBGetAllColumns 获取所有列信息（包含系统表）。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBGetAllColumns(config, dbName) {
    return $Call.ByID(3989146306, config, dbName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBGetColumns 获取列信息。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBGetColumns(config, dbName, tableName) {
    return $Call.ByID(1214038327, config, dbName, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBGetDatabases 获取数据库列表。
 * @param {connection$0.ConnectionConfig | null} config
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBGetDatabases(config) {
    return $Call.ByID(2424511702, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBGetForeignKeys 获取外键信息。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBGetForeignKeys(config, dbName, tableName) {
    return $Call.ByID(1538462816, config, dbName, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBGetIndexes 获取索引信息。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBGetIndexes(config, dbName, tableName) {
    return $Call.ByID(4080471820, config, dbName, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBGetTables 获取表列表。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBGetTables(config, dbName) {
    return $Call.ByID(3828957929, config, dbName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBGetTriggers 获取触发器信息。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBGetTriggers(config, dbName, tableName) {
    return $Call.ByID(3594716537, config, dbName, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBQuery 执行 SQL 并返回查询结果或受影响行数。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} query
 * @param {any[]} args
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBQuery(config, dbName, query, args) {
    return $Call.ByID(3791684532, config, dbName, query, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DBShowCreateTable 获取建表语句。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function DBShowCreateTable(config, dbName, tableName) {
    return $Call.ByID(480871923, config, dbName, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DefaultServiceShutdown 默认关闭实现
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceShutdown() {
    return $Call.ByID(1469706468);
}

/**
 * DefaultServiceStartup 默认启动实现
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceStartup(options) {
    return $Call.ByID(1135623207, options);
}

/**
 * ExportTable 导出表数据到 CSV、JSON 或 Markdown 文件。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @param {string} format
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function ExportTable(config, dbName, tableName, format) {
    return $Call.ByID(318759844, config, dbName, tableName, format).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ExportTypes() {
    return $Call.ByID(2134809601);
}

/**
 * ImportData 选择 CSV/JSON 文件并导入到目标表。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function ImportData(config, dbName, tableName) {
    return $Call.ByID(1651054087, config, dbName, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Logger 获取日志记录器
 * @returns {$CancellablePromise<slog$0.Logger | null>}
 */
export function Logger() {
    return $Call.ByID(3068554030).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * MySQLConnect 兼容历史 MySQL 入口，委托通用连接逻辑。
 * @param {connection$0.ConnectionConfig | null} config
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function MySQLConnect(config) {
    return $Call.ByID(2229832894, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * MySQLGetDatabases 兼容历史 MySQL 库列表入口。
 * @param {connection$0.ConnectionConfig | null} config
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function MySQLGetDatabases(config) {
    return $Call.ByID(2617653006, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * MySQLGetTables 兼容历史 MySQL 表列表入口。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function MySQLGetTables(config, dbName) {
    return $Call.ByID(981327009, config, dbName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * MySQLQuery 兼容历史 MySQL 查询入口，委托通用查询逻辑。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} query
 * @param {any[]} args
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function MySQLQuery(config, dbName, query, args) {
    return $Call.ByID(210759500, config, dbName, query, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * MySQLShowCreateTable 兼容历史 MySQL 建表语句入口。
 * @param {connection$0.ConnectionConfig | null} config
 * @param {string} dbName
 * @param {string} tableName
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function MySQLShowCreateTable(config, dbName, tableName) {
    return $Call.ByID(3067056043, config, dbName, tableName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * OpenSQLFile 选择 SQL 文件并返回内容。
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function OpenSQLFile() {
    return $Call.ByID(3103593168).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Registry 获取窗口注册表
 * @returns {$CancellablePromise<window$0.WindowRegistry | null>}
 */
export function Registry() {
    return $Call.ByID(591227737).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SetAppManager 设置窗口管理器
 * @param {window$0.AppManager | null} am
 * @returns {$CancellablePromise<void>}
 */
export function SetAppManager(am) {
    return $Call.ByID(2501546144, am);
}

/**
 * SetContext 设置上下文
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(3003349405);
}

/**
 * SetRegistry 设置窗口注册表
 * @param {window$0.WindowRegistry | null} registry
 * @returns {$CancellablePromise<void>}
 */
export function SetRegistry(registry) {
    return $Call.ByID(1269639241, registry);
}

/**
 * TestConnection 测试数据库连接，成功则返回成功消息，失败则返回错误信息
 * @param {connection$0.ConnectionConfig | null} config
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function TestConnection(config) {
    return $Call.ByID(2811401830, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TypeOnly_ColumnDefinition 仅用于导出类型到前端绑定。
 * @returns {$CancellablePromise<connection$0.ColumnDefinition | null>}
 */
export function TypeOnly_ColumnDefinition() {
    return $Call.ByID(460122262).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = window$0.AppManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = connection$0.QueryResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = slog$0.Logger.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = window$0.WindowRegistry.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = connection$0.ColumnDefinition.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
