// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService 仅提供前端可调用接口，核心逻辑在 internal/git。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "../window/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

/**
 * App 获取应用实例
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function App() {
    return $Call.ByID(1621555814).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AppManager 获取窗口管理器
 * @returns {$CancellablePromise<window$0.AppManager | null>}
 */
export function AppManager() {
    return $Call.ByID(2178324261).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Context 获取上下文
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Context() {
    return $Call.ByID(644222842);
}

/**
 * DefaultServiceShutdown 默认关闭实现
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceShutdown() {
    return $Call.ByID(2961806477);
}

/**
 * DefaultServiceStartup 默认启动实现
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceStartup(options) {
    return $Call.ByID(1600740216, options);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ExportTypes() {
    return $Call.ByID(146531414);
}

/**
 * GetActiveRepo 获取当前激活仓库 key。
 * @returns {$CancellablePromise<types$0.GitActiveRepoResult | null>}
 */
export function GetActiveRepo() {
    return $Call.ByID(3740655407).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetInitialStatusEvent 首次手动获取 Git 状态事件数据（不依赖监听回调）。
 * repoKey 为空时使用当前激活仓库。
 * @param {string} repoKey
 * @returns {$CancellablePromise<types$0.GitStatusEventResult | null>}
 */
export function GetInitialStatusEvent(repoKey) {
    return $Call.ByID(497157383, repoKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetRepoStatus 获取指定仓库状态。
 * @param {string} repoKey
 * @returns {$CancellablePromise<types$0.GitRepoStatusResult | null>}
 */
export function GetRepoStatus(repoKey) {
    return $Call.ByID(1159143151, repoKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListRepos 获取所有已注册仓库。
 * @returns {$CancellablePromise<types$0.GitRepoListResult | null>}
 */
export function ListRepos() {
    return $Call.ByID(2644846976).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * Logger 获取日志记录器
 * @returns {$CancellablePromise<slog$0.Logger | null>}
 */
export function Logger() {
    return $Call.ByID(2103283115).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * RegisterRepo 注册仓库到管理器 map。
 * @param {string} repoKey
 * @param {string} path
 * @returns {$CancellablePromise<types$0.GitRepoInfoResult | null>}
 */
export function RegisterRepo(repoKey, path) {
    return $Call.ByID(2345652826, repoKey, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * Registry 获取窗口注册表
 * @returns {$CancellablePromise<window$0.WindowRegistry | null>}
 */
export function Registry() {
    return $Call.ByID(41174452).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * RemoveRepo 从管理器 map 中移除仓库。
 * @param {string} repoKey
 * @returns {$CancellablePromise<types$0.GitRemoveRepoResult | null>}
 */
export function RemoveRepo(repoKey) {
    return $Call.ByID(2480643879, repoKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * SetActiveRepo 设置激活仓库。autoStart=true 时自动开启该仓库监听，stopOthers=true 时停止其他仓库监听。
 * @param {string} repoKey
 * @param {boolean} autoStart
 * @param {boolean} stopOthers
 * @returns {$CancellablePromise<types$0.GitRepoInfoResult | null>}
 */
export function SetActiveRepo(repoKey, autoStart, stopOthers) {
    return $Call.ByID(2555112171, repoKey, autoStart, stopOthers).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * SetAppManager 设置窗口管理器
 * @param {window$0.AppManager | null} am
 * @returns {$CancellablePromise<void>}
 */
export function SetAppManager(am) {
    return $Call.ByID(4236870031, am);
}

/**
 * SetContext 设置上下文
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(1379242776);
}

/**
 * SetRegistry 设置窗口注册表
 * @param {window$0.WindowRegistry | null} registry
 * @returns {$CancellablePromise<void>}
 */
export function SetRegistry(registry) {
    return $Call.ByID(2180862498, registry);
}

/**
 * StartRepoWatch 启动指定仓库监听。
 * @param {string} repoKey
 * @param {number} intervalMs
 * @returns {$CancellablePromise<types$0.GitRepoInfoResult | null>}
 */
export function StartRepoWatch(repoKey, intervalMs) {
    return $Call.ByID(2462705764, repoKey, intervalMs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * StopAllRepoWatch 停止全部仓库监听。
 * @returns {$CancellablePromise<types$0.GitStopAllRepoWatchResult | null>}
 */
export function StopAllRepoWatch() {
    return $Call.ByID(1461198377).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * StopRepoWatch 停止指定仓库监听。
 * @param {string} repoKey
 * @returns {$CancellablePromise<types$0.GitRepoInfoResult | null>}
 */
export function StopRepoWatch(repoKey) {
    return $Call.ByID(2609754610, repoKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = window$0.AppManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = types$0.GitActiveRepoResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = types$0.GitStatusEventResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = types$0.GitRepoStatusResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = types$0.GitRepoListResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = slog$0.Logger.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = types$0.GitRepoInfoResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = window$0.WindowRegistry.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = types$0.GitRemoveRepoResult.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = types$0.GitStopAllRepoWatchResult.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
