// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MenuService 菜单管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "../connection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "../window/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * App 获取应用实例
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function App() {
    return $Call.ByID(1529485163).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AppManager 获取窗口管理器
 * @returns {$CancellablePromise<window$0.AppManager | null>}
 */
export function AppManager() {
    return $Call.ByID(3244925386).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Context 获取上下文
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Context() {
    return $Call.ByID(3868377491);
}

/**
 * CreateContextMenu 创建上下文菜单
 * @param {$models.MenuDefinition} definition
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function CreateContextMenu(definition) {
    return $Call.ByID(504556376, definition).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DefaultServiceShutdown 默认关闭实现
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceShutdown() {
    return $Call.ByID(3844701238);
}

/**
 * DefaultServiceStartup 默认启动实现
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceStartup(options) {
    return $Call.ByID(267372253, options);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ExportTypes() {
    return $Call.ByID(4204872927);
}

/**
 * GetMenuList 获取所有已注册的菜单列表
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function GetMenuList() {
    return $Call.ByID(2598466043).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Logger 获取日志记录器
 * @returns {$CancellablePromise<slog$0.Logger | null>}
 */
export function Logger() {
    return $Call.ByID(467137780).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Registry 获取窗口注册表
 * @returns {$CancellablePromise<window$0.WindowRegistry | null>}
 */
export function Registry() {
    return $Call.ByID(1095632711).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SetAppManager 设置窗口管理器
 * @param {window$0.AppManager | null} am
 * @returns {$CancellablePromise<void>}
 */
export function SetAppManager(am) {
    return $Call.ByID(3993799130, am);
}

/**
 * SetContext 设置上下文
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(2107857475);
}

/**
 * SetRegistry 设置窗口注册表
 * @param {window$0.WindowRegistry | null} registry
 * @returns {$CancellablePromise<void>}
 */
export function SetRegistry(registry) {
    return $Call.ByID(836566679, registry);
}

/**
 * UnregisterContextMenu 注销菜单
 * @param {string} menuID
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function UnregisterContextMenu(menuID) {
    return $Call.ByID(3374680966, menuID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * UpdateMenu 更新菜单
 * @param {$models.MenuUpdateRequest} request
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function UpdateMenu(request) {
    return $Call.ByID(877361238, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = window$0.AppManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = connection$0.QueryResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = slog$0.Logger.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = window$0.WindowRegistry.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
