// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DataSyncEvent 数据同步事件
 */
export class DataSyncEvent {
    /**
     * Creates a new DataSyncEvent instance.
     * @param {Partial<DataSyncEvent>} [$$source = {}] - The source object to create the DataSyncEvent.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * 发送窗口名称
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * 目标窗口（空 = 广播）
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("channel" in $$source)) {
            /**
             * 数据频道
             * @member
             * @type {string}
             */
            this["channel"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * 数据类型标识
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * 实际数据
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["data"] = {};
        }
        if (!("timestamp" in $$source)) {
            /**
             * 时间戳
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("id" in $$source)) {
            /**
             * 唯一消息ID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSyncEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataSyncEvent}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField4_0($$parsedSource["data"]);
        }
        return new DataSyncEvent(/** @type {Partial<DataSyncEvent>} */($$parsedSource));
    }
}

/**
 * InitialDataEntry 初始数据条目
 */
export class InitialDataEntry {
    /**
     * Creates a new InitialDataEntry instance.
     * @param {Partial<InitialDataEntry>} [$$source = {}] - The source object to create the InitialDataEntry.
     */
    constructor($$source = {}) {
        if (!("windowName" in $$source)) {
            /**
             * 目标窗口名称
             * @member
             * @type {string}
             */
            this["windowName"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * 源窗口名称
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * 实际数据
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["data"] = {};
        }
        if (!("timestamp" in $$source)) {
            /**
             * 创建时间戳
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("expiresAt" in $$source)) {
            /**
             * 过期时间戳
             * @member
             * @type {number}
             */
            this["expiresAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitialDataEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InitialDataEntry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new InitialDataEntry(/** @type {Partial<InitialDataEntry>} */($$parsedSource));
    }
}

/**
 * MenuClickEvent 菜单点击事件
 */
export class MenuClickEvent {
    /**
     * Creates a new MenuClickEvent instance.
     * @param {Partial<MenuClickEvent>} [$$source = {}] - The source object to create the MenuClickEvent.
     */
    constructor($$source = {}) {
        if (!("menuId" in $$source)) {
            /**
             * 菜单 ID
             * @member
             * @type {string}
             */
            this["menuId"] = "";
        }
        if (!("itemId" in $$source)) {
            /**
             * 菜单项 ID
             * @member
             * @type {string}
             */
            this["itemId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * 菜单项类型
             * @member
             * @type {MenuItemType}
             */
            this["type"] = MenuItemType.$zero;
        }
        if (!("label" in $$source)) {
            /**
             * 菜单项标签
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("checked" in $$source)) {
            /**
             * 是否选中（checkbox/radio）
             * @member
             * @type {boolean}
             */
            this["checked"] = false;
        }
        if (!("contextData" in $$source)) {
            /**
             * 菜单的上下文数据
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["contextData"] = {};
        }
        if (!("itemData" in $$source)) {
            /**
             * 菜单项的上下文数据
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["itemData"] = {};
        }
        if (!("timestamp" in $$source)) {
            /**
             * 点击时间戳
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("window" in $$source)) {
            /**
             * 触发窗口
             * @member
             * @type {string}
             */
            this["window"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuClickEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MenuClickEvent}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contextData" in $$parsedSource) {
            $$parsedSource["contextData"] = $$createField5_0($$parsedSource["contextData"]);
        }
        if ("itemData" in $$parsedSource) {
            $$parsedSource["itemData"] = $$createField6_0($$parsedSource["itemData"]);
        }
        return new MenuClickEvent(/** @type {Partial<MenuClickEvent>} */($$parsedSource));
    }
}

/**
 * MenuDefinition 菜单定义（用于前端创建菜单）
 */
export class MenuDefinition {
    /**
     * Creates a new MenuDefinition instance.
     * @param {Partial<MenuDefinition>} [$$source = {}] - The source object to create the MenuDefinition.
     */
    constructor($$source = {}) {
        if (!("menuId" in $$source)) {
            /**
             * 菜单 ID
             * @member
             * @type {string}
             */
            this["menuId"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * 菜单标签（可选）
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("window" in $$source)) {
            /**
             * 关联窗口
             * @member
             * @type {string}
             */
            this["window"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * 菜单项列表
             * @member
             * @type {MenuItemDefinition[]}
             */
            this["items"] = [];
        }
        if (!("contextData" in $$source)) {
            /**
             * 上下文数据（可选）
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["contextData"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MenuDefinition}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        if ("contextData" in $$parsedSource) {
            $$parsedSource["contextData"] = $$createField4_0($$parsedSource["contextData"]);
        }
        return new MenuDefinition(/** @type {Partial<MenuDefinition>} */($$parsedSource));
    }
}

/**
 * MenuItemDefinition 菜单项定义
 */
export class MenuItemDefinition {
    /**
     * Creates a new MenuItemDefinition instance.
     * @param {Partial<MenuItemDefinition>} [$$source = {}] - The source object to create the MenuItemDefinition.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 菜单项 ID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * 类型: item|checkbox|radio|separator|submenu
             * @member
             * @type {MenuItemType}
             */
            this["type"] = MenuItemType.$zero;
        }
        if (!("label" in $$source)) {
            /**
             * 标签
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("checked" in $$source)) {
            /**
             * 是否选中（checkbox/radio）
             * @member
             * @type {boolean | null}
             */
            this["checked"] = null;
        }
        if (!("shortcut" in $$source)) {
            /**
             * 快捷键
             * @member
             * @type {string | null}
             */
            this["shortcut"] = null;
        }
        if (!("enabled" in $$source)) {
            /**
             * 是否启用
             * @member
             * @type {boolean | null}
             */
            this["enabled"] = null;
        }
        if (!("items" in $$source)) {
            /**
             * 子菜单项（submenu）
             * @member
             * @type {MenuItemDefinition[]}
             */
            this["items"] = [];
        }
        if (!("contextData" in $$source)) {
            /**
             * 上下文数据
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["contextData"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuItemDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MenuItemDefinition}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField6_0($$parsedSource["items"]);
        }
        if ("contextData" in $$parsedSource) {
            $$parsedSource["contextData"] = $$createField7_0($$parsedSource["contextData"]);
        }
        return new MenuItemDefinition(/** @type {Partial<MenuItemDefinition>} */($$parsedSource));
    }
}

/**
 * MenuItemType 菜单项类型枚举
 * @readonly
 * @enum {string}
 */
export const MenuItemType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 普通菜单项
     */
    MenuItemTypeItem: "item",

    /**
     * 复选框
     */
    MenuItemTypeCheckbox: "checkbox",

    /**
     * 单选框
     */
    MenuItemTypeRadio: "radio",

    /**
     * 分隔符
     */
    MenuItemTypeSeparator: "separator",

    /**
     * 子菜单
     */
    MenuItemTypeSubmenu: "submenu",
};

/**
 * MenuUpdateRequest 菜单更新请求
 */
export class MenuUpdateRequest {
    /**
     * Creates a new MenuUpdateRequest instance.
     * @param {Partial<MenuUpdateRequest>} [$$source = {}] - The source object to create the MenuUpdateRequest.
     */
    constructor($$source = {}) {
        if (!("menuId" in $$source)) {
            /**
             * 菜单 ID
             * @member
             * @type {string}
             */
            this["menuId"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * 新的菜单项列表
             * @member
             * @type {MenuItemDefinition[]}
             */
            this["items"] = [];
        }
        if (!("contextData" in $$source)) {
            /**
             * 新的上下文数据
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["contextData"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuUpdateRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MenuUpdateRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        if ("contextData" in $$parsedSource) {
            $$parsedSource["contextData"] = $$createField2_0($$parsedSource["contextData"]);
        }
        return new MenuUpdateRequest(/** @type {Partial<MenuUpdateRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = MenuItemDefinition.createFrom;
const $$createType2 = $Create.Array($$createType1);
