// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService 终端服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "../terminal/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "../window/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

/**
 * App 获取应用实例
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function App() {
    return $Call.ByID(2361704398).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AppManager 获取窗口管理器
 * @returns {$CancellablePromise<window$0.AppManager | null>}
 */
export function AppManager() {
    return $Call.ByID(3996337405).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Close 关闭终端会话
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function Close(sessionID) {
    return $Call.ByID(1182121713, sessionID);
}

/**
 * Context 获取上下文
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Context() {
    return $Call.ByID(3780404050);
}

/**
 * Create 创建新的终端会话
 * @param {terminal$0.TerminalConfig} config
 * @returns {$CancellablePromise<types$0.TerminalCreateResult | null>}
 */
export function Create(config) {
    return $Call.ByID(313997307, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DefaultServiceShutdown 默认关闭实现
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceShutdown() {
    return $Call.ByID(3366665557);
}

/**
 * DefaultServiceStartup 默认启动实现
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceStartup(options) {
    return $Call.ByID(355774208, options);
}

/**
 * Emit 实现 EventEmitter 接口
 * @param {string} event
 * @param {any} data
 * @returns {$CancellablePromise<void>}
 */
export function Emit(event, data) {
    return $Call.ByID(3931598064, event, data);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ExportTypes() {
    return $Call.ByID(4027472782);
}

/**
 * ListExecutableCommands 获取终端配置环境中的可执行命令，并返回对应终端的默认命令
 * @param {terminal$0.ShellType} shellType
 * @returns {$CancellablePromise<types$0.TerminalListExecutableCommandsResult | null>}
 */
export function ListExecutableCommands(shellType) {
    return $Call.ByID(302539465, shellType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Logger 获取日志记录器
 * @returns {$CancellablePromise<slog$0.Logger | null>}
 */
export function Logger() {
    return $Call.ByID(186884995).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * Registry 获取窗口注册表
 * @returns {$CancellablePromise<window$0.WindowRegistry | null>}
 */
export function Registry() {
    return $Call.ByID(3166104300).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * Resize 调整终端大小
 * @param {string} sessionID
 * @param {number} rows
 * @param {number} cols
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionID, rows, cols) {
    return $Call.ByID(3021238275, sessionID, rows, cols);
}

/**
 * SetAppManager 设置窗口管理器
 * @param {window$0.AppManager | null} am
 * @returns {$CancellablePromise<void>}
 */
export function SetAppManager(am) {
    return $Call.ByID(970821975, am);
}

/**
 * SetContext 设置上下文
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(1417148096);
}

/**
 * SetRegistry 设置窗口注册表
 * @param {window$0.WindowRegistry | null} registry
 * @returns {$CancellablePromise<void>}
 */
export function SetRegistry(registry) {
    return $Call.ByID(1537769002, registry);
}

/**
 * TestConfig 测试终端配置参数是否有效
 * @param {terminal$0.TerminalConfig} config
 * @returns {$CancellablePromise<types$0.TerminalTestConfigResult | null>}
 */
export function TestConfig(config) {
    return $Call.ByID(1405987981, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * UpdateWorkPath 更新工作路径（由 shell hook 触发）
 * @param {string} sessionID
 * @param {string} newPwd
 * @returns {$CancellablePromise<void>}
 */
export function UpdateWorkPath(sessionID, newPwd) {
    return $Call.ByID(471194792, sessionID, newPwd);
}

/**
 * Write 向终端写入用户输入
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Write(sessionID, data) {
    return $Call.ByID(2238547742, sessionID, data);
}

/**
 * WriteCommand 写入命令并返回 block ID
 * 用于追踪命令输出，实现 block 关联（兼容旧调用，不要求前端提供 block ID）。
 * @param {string} sessionID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function WriteCommand(sessionID, command) {
    return $Call.ByID(1886423823, sessionID, command);
}

/**
 * WriteCommandWithBlock 写入命令并复用前端提供的 block ID。
 * 该方法用于保证命令流式输出与前端 block 在首包输出前就能完成绑定。
 * @param {string} sessionID
 * @param {string} blockID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function WriteCommandWithBlock(sessionID, blockID, command) {
    return $Call.ByID(1330753672, sessionID, blockID, command);
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = window$0.AppManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = types$0.TerminalCreateResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = types$0.TerminalListExecutableCommandsResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = slog$0.Logger.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = window$0.WindowRegistry.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = types$0.TerminalTestConfigResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
