// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 窗口管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../../../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "../connection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "../window/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";

/**
 * App 获取应用实例
 * @returns {$CancellablePromise<application$0.App | null>}
 */
export function App() {
    return $Call.ByID(1052801626).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AppManager 获取窗口管理器
 * @returns {$CancellablePromise<window$0.AppManager | null>}
 */
export function AppManager() {
    return $Call.ByID(3498424641).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ClosePage 关闭页面
 * @param {string} pageId
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function ClosePage(pageId) {
    return $Call.ByID(1988448198, pageId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Context 获取上下文
 * @returns {$CancellablePromise<context$0.Context>}
 */
export function Context() {
    return $Call.ByID(2106030198);
}

/**
 * DefaultServiceShutdown 默认关闭实现
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceShutdown() {
    return $Call.ByID(878153105);
}

/**
 * DefaultServiceStartup 默认启动实现
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function DefaultServiceStartup(options) {
    return $Call.ByID(3681834508, options);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ExportTypes() {
    return $Call.ByID(444631538);
}

/**
 * GetPageList 获取所有可用页面列表
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function GetPageList() {
    return $Call.ByID(4115407558).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} pageId
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function GetWindowNameByPageID(pageId) {
    return $Call.ByID(1128706045, pageId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Logger 获取日志记录器
 * @returns {$CancellablePromise<slog$0.Logger | null>}
 */
export function Logger() {
    return $Call.ByID(3030831263).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * OpenPage 打开页面（统一 API）
 * @param {string} pageId
 * @returns {$CancellablePromise<connection$0.QueryResult | null>}
 */
export function OpenPage(pageId) {
    return $Call.ByID(956549960, pageId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Registry 获取窗口注册表
 * @returns {$CancellablePromise<window$0.WindowRegistry | null>}
 */
export function Registry() {
    return $Call.ByID(2842401608).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SetAppManager 设置窗口管理器
 * @param {window$0.AppManager | null} am
 * @returns {$CancellablePromise<void>}
 */
export function SetAppManager(am) {
    return $Call.ByID(3832490787, am);
}

/**
 * SetContext 设置上下文
 * @returns {$CancellablePromise<void>}
 */
export function SetContext() {
    return $Call.ByID(1704648908);
}

/**
 * SetRegistry 设置窗口注册表
 * @param {window$0.WindowRegistry | null} registry
 * @returns {$CancellablePromise<void>}
 */
export function SetRegistry(registry) {
    return $Call.ByID(3120211646, registry);
}

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = window$0.AppManager.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = connection$0.QueryResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = slog$0.Logger.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = window$0.WindowRegistry.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
