// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChangeSet 是一组数据库变更的结构体
 * 包含插入、更新和删除的变更数据，用于批量应用变更时传递数据
 */
export class ChangeSet {
    /**
     * Creates a new ChangeSet instance.
     * @param {Partial<ChangeSet>} [$$source = {}] - The source object to create the ChangeSet.
     */
    constructor($$source = {}) {
        if (!("inserts" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["inserts"] = [];
        }
        if (!("updates" in $$source)) {
            /**
             * @member
             * @type {UpdateRow[]}
             */
            this["updates"] = [];
        }
        if (!("deletes" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[]}
             */
            this["deletes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeSet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChangeSet}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inserts" in $$parsedSource) {
            $$parsedSource["inserts"] = $$createField0_0($$parsedSource["inserts"]);
        }
        if ("updates" in $$parsedSource) {
            $$parsedSource["updates"] = $$createField1_0($$parsedSource["updates"]);
        }
        if ("deletes" in $$parsedSource) {
            $$parsedSource["deletes"] = $$createField2_0($$parsedSource["deletes"]);
        }
        return new ChangeSet(/** @type {Partial<ChangeSet>} */($$parsedSource));
    }
}

/**
 * ColumnDefinition 是数据库列的定义结构体
 * 包含列名、类型、是否可空、键类型、默认值、额外信息和注释等信息
 */
export class ColumnDefinition {
    /**
     * Creates a new ColumnDefinition instance.
     * @param {Partial<ColumnDefinition>} [$$source = {}] - The source object to create the ColumnDefinition.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            /**
             * "YES" or "NO"
             * @member
             * @type {string}
             */
            this["nullable"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * "PRI" for primary key, "MUL" for foreign key, "UNI" for others
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["default"] = null;
        }
        if (!("extra" in $$source)) {
            /**
             * auto_increment
             * @member
             * @type {string}
             */
            this["extra"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnDefinition}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnDefinition(/** @type {Partial<ColumnDefinition>} */($$parsedSource));
    }
}

/**
 * ConnectionConfig 是数据库连接的配置结构体
 * 包含连接类型、主机、端口、用户、密码、数据库名称以及SSH配置等信息
 */
export class ConnectionConfig {
    /**
     * Creates a new ConnectionConfig instance.
     * @param {Partial<ConnectionConfig>} [$$source = {}] - The source object to create the ConnectionConfig.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {ConnectionType}
             */
            this["type"] = ConnectionType.$zero;
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["database"] = undefined;
        }
        if (!("useSSH" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useSSH"] = false;
        }
        if (!("ssh" in $$source)) {
            /**
             * @member
             * @type {SSHConfig | null}
             */
            this["ssh"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * 用于自定义连接
             * @member
             * @type {string | undefined}
             */
            this["driver"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 用于自定义连接
             * @member
             * @type {string | undefined}
             */
            this["dsn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 连接超时时间，单位秒
             * @member
             * @type {number | undefined}
             */
            this["timeout"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionConfig}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField7_0($$parsedSource["ssh"]);
        }
        return new ConnectionConfig(/** @type {Partial<ConnectionConfig>} */($$parsedSource));
    }
}

/**
 * ConnectionType 数据库连接类型
 * @readonly
 * @enum {string}
 */
export const ConnectionType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * MySQL 数据库
     */
    ConnectionTypeMySQL: "mysql",

    /**
     * PostgreSQL 数据库
     */
    ConnectionTypePostgreSQL: "postgresql",

    /**
     * Kingbase 数据库
     */
    ConnectionTypeKingbase: "kingbase",

    /**
     * HighGo 数据库
     */
    ConnectionTypeHighGo: "highgo",

    /**
     * VastBase 数据库
     */
    ConnectionTypeVastBase: "vastbase",

    /**
     * TDengine 数据库
     */
    ConnectionTypeTDengine: "tdengine",

    /**
     * MariaDB 数据库
     */
    ConnectionTypeMariaDB: "mariadb",

    /**
     * MongoDB 数据库
     */
    ConnectionTypeMongoDB: "mongodb",

    /**
     * 达梦数据库
     */
    ConnectionTypeDameng: "dameng",

    /**
     * SQL Server 数据库
     */
    ConnectionTypeSQLServer: "sqlserver",

    /**
     * SQLite 数据库
     */
    ConnectionTypeSQLite: "sqlite",

    /**
     * 自定义连接
     */
    ConnectionTypeCustom: "custom",
};

/**
 * QueryResult 是查询结果的结构体
 * 包含查询是否成功、消息、数据和字段列表等信息
 */
export class QueryResult {
    /**
     * Creates a new QueryResult instance.
     * @param {Partial<QueryResult>} [$$source = {}] - The source object to create the QueryResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["data"] = null;
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField3_0($$parsedSource["fields"]);
        }
        return new QueryResult(/** @type {Partial<QueryResult>} */($$parsedSource));
    }
}

/**
 * SSHConfig 是SSH连接的配置结构体
 * 包含主机、端口、用户、密码和密钥路径等信息
 */
export class SSHConfig {
    /**
     * Creates a new SSHConfig instance.
     * @param {Partial<SSHConfig>} [$$source = {}] - The source object to create the SSHConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("keyPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfig(/** @type {Partial<SSHConfig>} */($$parsedSource));
    }
}

/**
 * UpdateRow 是更新操作中包含主键和值的结构体
 * 用于表示一行更新的数据，其中Keys包含主键列和值，Values包含要更新的列和值
 */
export class UpdateRow {
    /**
     * Creates a new UpdateRow instance.
     * @param {Partial<UpdateRow>} [$$source = {}] - The source object to create the UpdateRow.
     */
    constructor($$source = {}) {
        if (!("keys" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["keys"] = {};
        }
        if (!("values" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["values"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateRow}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField0_0($$parsedSource["keys"]);
        }
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField1_0($$parsedSource["values"]);
        }
        return new UpdateRow(/** @type {Partial<UpdateRow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = UpdateRow.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = SSHConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
