// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * NapCatStatus 描述当前 NapCat 连接与登录状态快照。
 */
export class NapCatStatus {
    /**
     * Creates a new NapCatStatus instance.
     * @param {Partial<NapCatStatus>} [$$source = {}] - The source object to create the NapCatStatus.
     */
    constructor($$source = {}) {
        if (!("containerRunning" in $$source)) {
            /**
             * NapCat 进程/容器是否运行
             * @member
             * @type {boolean}
             */
            this["containerRunning"] = false;
        }
        if (!("wsConnected" in $$source)) {
            /**
             * OneBot WS 端口是否可达
             * @member
             * @type {boolean}
             */
            this["wsConnected"] = false;
        }
        if (!("httpAvailable" in $$source)) {
            /**
             * OneBot HTTP 端口是否可达
             * @member
             * @type {boolean}
             */
            this["httpAvailable"] = false;
        }
        if (!("qqLoggedIn" in $$source)) {
            /**
             * QQ 是否已登录
             * @member
             * @type {boolean}
             */
            this["qqLoggedIn"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * 当前登录 QQ 昵称
             * @member
             * @type {string | undefined}
             */
            this["qqNickname"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 当前登录 QQ 号
             * @member
             * @type {string | undefined}
             */
            this["qqId"] = undefined;
        }
        if (!("lastCheck" in $$source)) {
            /**
             * 最近一次探测时间
             * @member
             * @type {time$0.Time}
             */
            this["lastCheck"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * 最近一次在线时间
             * @member
             * @type {time$0.Time | undefined}
             */
            this["lastOnline"] = undefined;
        }
        if (!("reconnectCount" in $$source)) {
            /**
             * 当前累计重连次数
             * @member
             * @type {number}
             */
            this["reconnectCount"] = 0;
        }
        if (!("maxReconnect" in $$source)) {
            /**
             * 自动重连上限
             * @member
             * @type {number}
             */
            this["maxReconnect"] = 0;
        }
        if (!("autoReconnect" in $$source)) {
            /**
             * 是否启用自动重连
             * @member
             * @type {boolean}
             */
            this["autoReconnect"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * 总体状态：online/offline/reconnecting/login_expired/stopped
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NapCatStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NapCatStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NapCatStatus(/** @type {Partial<NapCatStatus>} */($$parsedSource));
    }
}

/**
 * ReconnectLog 记录一次重连尝试的结果。
 */
export class ReconnectLog {
    /**
     * Creates a new ReconnectLog instance.
     * @param {Partial<ReconnectLog>} [$$source = {}] - The source object to create the ReconnectLog.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * 重连触发时间
             * @member
             * @type {time$0.Time}
             */
            this["time"] = null;
        }
        if (!("reason" in $$source)) {
            /**
             * 重连原因
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * 是否重连成功
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * 补充说明
             * @member
             * @type {string | undefined}
             */
            this["detail"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconnectLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReconnectLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReconnectLog(/** @type {Partial<ReconnectLog>} */($$parsedSource));
    }
}
