// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * Task 安装任务
 */
export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 任务唯一标识。
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 任务名称。
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * 任务类型，如 install_software/install_openclaw。
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 当前任务状态。
             * @member
             * @type {TaskStatus}
             */
            this["status"] = TaskStatus.$zero;
        }
        if (!("progress" in $$source)) {
            /**
             * 当前进度，范围 0-100。
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("log" in $$source)) {
            /**
             * 任务日志列表。
             * @member
             * @type {string[]}
             */
            this["log"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * 任务失败时的错误信息。
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * 任务创建时间。
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * 任务最近更新时间。
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField5_0($$parsedSource["log"]);
        }
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

/**
 * TaskStatus 任务状态
 * @readonly
 * @enum {string}
 */
export const TaskStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusPending: "pending",
    StatusRunning: "running",
    StatusSuccess: "success",
    StatusFailed: "failed",
    StatusCanceled: "canceled",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
