// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppManager 管理多个窗口的应用程序
 */
export class AppManager {
    /**
     * Creates a new AppManager instance.
     * @param {Partial<AppManager>} [$$source = {}] - The source object to create the AppManager.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppManager}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppManager(/** @type {Partial<AppManager>} */($$parsedSource));
    }
}

/**
 * WindowRegistry 窗口注册表
 */
export class WindowRegistry {
    /**
     * Creates a new WindowRegistry instance.
     * @param {Partial<WindowRegistry>} [$$source = {}] - The source object to create the WindowRegistry.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowRegistry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowRegistry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowRegistry(/** @type {Partial<WindowRegistry>} */($$parsedSource));
    }
}
