// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";

/**
 * 已安装到磁盘的插件。
 */
export class InstalledPlugin {
    /**
     * Creates a new InstalledPlugin instance.
     * @param {Partial<InstalledPlugin>} [$$source = {}] - The source object to create the InstalledPlugin.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 插件唯一标识。
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 插件展示名称。
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * 插件版本号。
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * 插件作者信息。
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 插件功能简介。
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件主页地址。
             * @member
             * @type {string | undefined}
             */
            this["homepage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件源码仓库地址。
             * @member
             * @type {string | undefined}
             */
            this["repository"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件许可证标识。
             * @member
             * @type {string | undefined}
             */
            this["license"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件分类（如 basic/ai/message/fun/tool）。
             * @member
             * @type {string | undefined}
             */
            this["category"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件标签列表。
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件图标地址或路径。
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 要求的最小 OpenClaw 版本。
             * @member
             * @type {string | undefined}
             */
            this["minOpenClaw"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 要求的最小面板版本。
             * @member
             * @type {string | undefined}
             */
            this["minPanel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件主入口脚本文件。
             * @member
             * @type {string | undefined}
             */
            this["entryPoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件配置 JSON Schema。
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["configSchema"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件依赖及版本约束。
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["dependencies"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件请求的权限列表。
             * @member
             * @type {string[] | undefined}
             */
            this["permissions"] = undefined;
        }
        if (!("enabled" in $$source)) {
            /**
             * 插件当前是否启用。
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("installedAt" in $$source)) {
            /**
             * 首次安装时间（RFC3339）。
             * @member
             * @type {string}
             */
            this["installedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 最近更新时间（RFC3339）。
             * @member
             * @type {string | undefined}
             */
            this["updatedAt"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * 安装来源（registry/local/github/custom/npm）。
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("dir" in $$source)) {
            /**
             * 插件实际安装目录。
             * @member
             * @type {string}
             */
            this["dir"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件运行配置。
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["config"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 最近插件日志行缓存。
             * @member
             * @type {string[] | undefined}
             */
            this["logLines"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledPlugin instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InstalledPlugin}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType0;
        const $$createField22_0 = $$createType2;
        const $$createField23_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField9_0($$parsedSource["tags"]);
        }
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField15_0($$parsedSource["dependencies"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField16_0($$parsedSource["permissions"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField22_0($$parsedSource["config"]);
        }
        if ("logLines" in $$parsedSource) {
            $$parsedSource["logLines"] = $$createField23_0($$parsedSource["logLines"]);
        }
        return new InstalledPlugin(/** @type {Partial<InstalledPlugin>} */($$parsedSource));
    }
}

/**
 * 插件仓库数据结构。
 */
export class Registry {
    /**
     * Creates a new Registry instance.
     * @param {Partial<Registry>} [$$source = {}] - The source object to create the Registry.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * 仓库索引版本号。
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * 仓库更新时间（RFC3339）。
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("plugins" in $$source)) {
            /**
             * 仓库内插件列表。
             * @member
             * @type {RegistryPlugin[]}
             */
            this["plugins"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Registry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Registry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField2_0($$parsedSource["plugins"]);
        }
        return new Registry(/** @type {Partial<Registry>} */($$parsedSource));
    }
}

/**
 * 插件仓库中的插件项。
 */
export class RegistryPlugin {
    /**
     * Creates a new RegistryPlugin instance.
     * @param {Partial<RegistryPlugin>} [$$source = {}] - The source object to create the RegistryPlugin.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 插件唯一标识。
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 插件展示名称。
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * 插件版本号。
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * 插件作者信息。
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 插件功能简介。
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件主页地址。
             * @member
             * @type {string | undefined}
             */
            this["homepage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件源码仓库地址。
             * @member
             * @type {string | undefined}
             */
            this["repository"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件许可证标识。
             * @member
             * @type {string | undefined}
             */
            this["license"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件分类（如 basic/ai/message/fun/tool）。
             * @member
             * @type {string | undefined}
             */
            this["category"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件标签列表。
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件图标地址或路径。
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 要求的最小 OpenClaw 版本。
             * @member
             * @type {string | undefined}
             */
            this["minOpenClaw"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 要求的最小面板版本。
             * @member
             * @type {string | undefined}
             */
            this["minPanel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件主入口脚本文件。
             * @member
             * @type {string | undefined}
             */
            this["entryPoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件配置 JSON Schema。
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["configSchema"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件依赖及版本约束。
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["dependencies"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件请求的权限列表。
             * @member
             * @type {string[] | undefined}
             */
            this["permissions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 下载次数统计。
             * @member
             * @type {number | undefined}
             */
            this["downloads"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 收藏/点赞统计。
             * @member
             * @type {number | undefined}
             */
            this["stars"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件归档下载地址。
             * @member
             * @type {string | undefined}
             */
            this["downloadUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件源码仓库地址。
             * @member
             * @type {string | undefined}
             */
            this["gitUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 仓库内需要安装的子目录。
             * @member
             * @type {string | undefined}
             */
            this["installSubDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 可直接安装的 npm 包名。
             * @member
             * @type {string | undefined}
             */
            this["npmPackage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件截图地址。
             * @member
             * @type {string | undefined}
             */
            this["screenshot"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 插件说明文档地址或内容索引。
             * @member
             * @type {string | undefined}
             */
            this["readme"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistryPlugin instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RegistryPlugin}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField9_0($$parsedSource["tags"]);
        }
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField15_0($$parsedSource["dependencies"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField16_0($$parsedSource["permissions"]);
        }
        return new RegistryPlugin(/** @type {Partial<RegistryPlugin>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = RegistryPlugin.createFrom;
const $$createType4 = $Create.Array($$createType3);
