// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyChanges'](arg1, arg2, arg3, arg4);
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['main']['App']['CreateDatabase'](arg1, arg2);
}

export function DBConnect(arg1) {
  return window['go']['main']['App']['DBConnect'](arg1);
}

export function DBGetAllColumns(arg1, arg2) {
  return window['go']['main']['App']['DBGetAllColumns'](arg1, arg2);
}

export function DBGetColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBGetColumns'](arg1, arg2, arg3);
}

export function DBGetDatabases(arg1) {
  return window['go']['main']['App']['DBGetDatabases'](arg1);
}

export function DBGetForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBGetForeignKeys'](arg1, arg2, arg3);
}

export function DBGetIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBGetIndexes'](arg1, arg2, arg3);
}

export function DBGetTables(arg1, arg2) {
  return window['go']['main']['App']['DBGetTables'](arg1, arg2);
}

export function DBGetTriggers(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBGetTriggers'](arg1, arg2, arg3);
}

export function DBQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBQuery'](arg1, arg2, arg3);
}

export function DBShowCreateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBShowCreateTable'](arg1, arg2, arg3);
}

export function ExportTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportTable'](arg1, arg2, arg3, arg4);
}

export function ImportData(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportData'](arg1, arg2, arg3);
}

export function MySQLConnect(arg1) {
  return window['go']['main']['App']['MySQLConnect'](arg1);
}

export function MySQLGetDatabases(arg1) {
  return window['go']['main']['App']['MySQLGetDatabases'](arg1);
}

export function MySQLGetTables(arg1, arg2) {
  return window['go']['main']['App']['MySQLGetTables'](arg1, arg2);
}

export function MySQLQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['MySQLQuery'](arg1, arg2, arg3);
}

export function MySQLShowCreateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['MySQLShowCreateTable'](arg1, arg2, arg3);
}

export function OpenSQLFile() {
  return window['go']['main']['App']['OpenSQLFile']();
}
