// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * Status 描述 OpenClaw 进程状态。
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * 是否运行中
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("pid" in $$source)) {
            /**
             * 进程 ID（外部托管时可能为 0）
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 启动时间
             * @member
             * @type {time$0.Time | undefined}
             */
            this["startedAt"] = undefined;
        }
        if (!("uptime" in $$source)) {
            /**
             * 运行时长（秒）
             * @member
             * @type {number}
             */
            this["uptime"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 最近一次退出码
             * @member
             * @type {number | undefined}
             */
            this["exitCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 是否为 daemon fork 模式
             * @member
             * @type {boolean | undefined}
             */
            this["daemonized"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 是否由外部进程管理
             * @member
             * @type {boolean | undefined}
             */
            this["managedExternally"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}
